// Prueba de flujo: registrar una sesión, abrir modales y capturas de estados.
const path = require('path');
const { chromium } = require('playwright');
const OUT = path.join(__dirname, 'out');
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: 'es-ES', timezoneId: 'Europe/Madrid' });
  const p = await ctx.newPage();
  const errs = [];
  p.on('pageerror', e => errs.push(e.message));
  await p.clock.setFixedTime(new Date('2026-10-08T11:20:00+02:00'));
  await p.goto('file://' + path.join(OUT, 'index.html'));
  await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.addStyleTag({ content: '*,*::before,*::after{animation:none!important}' });
  await p.waitForSelector('#cSesion .pill');
  await p.click('.tramo[data-tramo="t5"]');
  const pills = await p.$$('#cSesion [data-alu]');
  await pills[0].click(); if (pills[1]) await pills[1].click();
  await p.click('[data-mat="Lengua"]');
  await p.click('#quick [data-s]');
  await p.fill('#trab', 'Lectura en voz alta. Muy bien la entonación.');
  await p.click('[data-star="4"]');
  await p.screenshot({ path: path.join(OUT, 'f1-relleno.png') });
  await p.click('#guardar');
  await p.waitForTimeout(500);
  const banner = await p.textContent('#banner');
  console.log('Banner tras guardar:', banner.trim().slice(0, 80));
  await p.click('#addAlu'); await p.fill('#busAlu', 'zz Nuevo Alumno'); await p.waitForTimeout(200);
  await p.screenshot({ path: path.join(OUT, 'f2-anadir.png') });
  await p.click('#crearAlu'); await p.waitForTimeout(400);
  console.log('Extra añadido:', await p.$$eval('#cSesion .pill.extra', e => e.map(x => x.textContent)));
  await p.click('[data-view="diario"]'); await p.waitForTimeout(300);
  await p.click('.entry'); await p.waitForTimeout(300);
  await p.screenshot({ path: path.join(OUT, 'f3-detalle.png') });
  await p.click('#sheet [data-ficha]'); await p.waitForTimeout(300);
  await p.screenshot({ path: path.join(OUT, 'f4-ficha.png') });
  await p.keyboard.press('Escape');
  await p.click('[data-view="ajustes"]'); await p.click('[data-tab="horarios"]'); await p.waitForTimeout(200);
  await p.screenshot({ path: path.join(OUT, 'f5-horarios.png'), fullPage: true });
  await p.click('.sched .cell'); await p.waitForTimeout(200);
  await p.screenshot({ path: path.join(OUT, 'f6-celda.png') });
  await p.keyboard.press('Escape');
  await p.click('[data-tab="alumnado"]'); await p.waitForTimeout(200);
  await p.screenshot({ path: path.join(OUT, 'f7-alumnado.png'), fullPage: true });
  // Edición desde diario
  await p.click('[data-view="diario"]'); await p.click('.seg [data-v="mios"]'); await p.waitForTimeout(200);
  await p.click('.entry'); await p.click('#edit'); await p.waitForTimeout(300);
  console.log('Editando:', (await p.textContent('#banner')).trim().slice(0, 60), '| boton:', await p.textContent('#guardar'));
  await b.close();
  console.log(errs.length ? 'ERRORES: ' + errs.join(' | ') : 'Sin errores JS');
})();
